"""Loader for the bundled NIST SP 800-53 control catalogs and Rev4->Rev5 mapping.

The catalog JSON is generated by ``scripts/fetch_catalogs.py`` from the official
NIST OSCAL content and committed under ``data/`` (bundled, not fetched at runtime,
because private/GovCloud deployments have no internet egress).

Resolution order for the data directory:
  1. ``RMF_DATA_DIR`` env var, if set.
  2. A ``data`` dir found by walking up from this file (covers `PYTHONPATH=src`
     dev/test where the repo root holds `data/`, and the Lambda package where
     `data/` sits beside `rmf_migrator/` at the archive root).
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path


class CatalogError(RuntimeError):
    pass


def _find_data_dir() -> Path:
    env = os.environ.get("RMF_DATA_DIR")
    if env:
        path = Path(env)
        if (path / "catalogs").is_dir():
            return path
        raise CatalogError(f"RMF_DATA_DIR={env} has no catalogs/ subdirectory")

    for parent in Path(__file__).resolve().parents:
        candidate = parent / "data"
        if (candidate / "catalogs").is_dir():
            return candidate
    raise CatalogError("could not locate bundled data/ directory (set RMF_DATA_DIR)")


@dataclass(frozen=True)
class Control:
    id: str
    title: str
    family: str
    is_enhancement: bool
    withdrawn: bool


@dataclass(frozen=True)
class MappingRow:
    rev4_id: str | None
    rev5_ids: tuple[str, ...]
    relationship: str  # same | renamed | withdrawn | new | merged | split | incorporated
    source: str


class Catalog:
    """Indexed set of controls for one revision."""

    def __init__(self, revision: str, controls: list[Control]) -> None:
        self.revision = revision
        self._by_id = {c.id: c for c in controls}

    def __contains__(self, control_id: str) -> bool:
        return control_id in self._by_id

    def get(self, control_id: str) -> Control | None:
        return self._by_id.get(control_id)

    def all(self) -> list[Control]:
        return list(self._by_id.values())

    def families(self) -> list[str]:
        return sorted({c.family for c in self._by_id.values()})

    def validate_ids(self, control_ids: list[str]) -> tuple[list[str], list[str]]:
        """Split ``control_ids`` into (known, unknown) for this revision."""
        known = [cid for cid in control_ids if cid in self._by_id]
        unknown = [cid for cid in control_ids if cid not in self._by_id]
        return known, unknown


class Crosswalk:
    """Rev 4 -> Rev 5 disposition lookup."""

    def __init__(self, rows: list[MappingRow]) -> None:
        self._rows = rows
        self._by_rev4 = {r.rev4_id: r for r in rows if r.rev4_id is not None}

    def disposition(self, rev4_id: str) -> MappingRow | None:
        return self._by_rev4.get(rev4_id)

    def rev5_for(self, rev4_id: str) -> list[str]:
        row = self._by_rev4.get(rev4_id)
        return list(row.rev5_ids) if row else []

    def new_in_rev5(self) -> list[str]:
        """Rev 5 controls with no Rev 4 predecessor (e.g. the SR family)."""
        out: list[str] = []
        for row in self._rows:
            if row.relationship == "new":
                out.extend(row.rev5_ids)
        return sorted(set(out))

    def rows(self) -> list[MappingRow]:
        return list(self._rows)


def _load_controls(revision_file: str) -> list[Control]:
    data_dir = _find_data_dir()
    raw = json.loads((data_dir / "catalogs" / revision_file).read_text())
    return [
        Control(
            id=c["id"],
            title=c["title"],
            family=c["family"],
            is_enhancement=c["is_enhancement"],
            withdrawn=c["withdrawn"],
        )
        for c in raw["controls"]
    ]


@lru_cache(maxsize=1)
def rev4_catalog() -> Catalog:
    return Catalog("4", _load_controls("rev4_controls.json"))


@lru_cache(maxsize=1)
def rev5_catalog() -> Catalog:
    return Catalog("5", _load_controls("rev5_controls.json"))


BASELINE_NAMES = ("low", "moderate", "high")


@lru_cache(maxsize=8)
def baseline_controls(name: str) -> frozenset[str]:
    """Return the Rev 5 control ids required by a baseline (low/moderate/high)."""
    if name not in BASELINE_NAMES:
        raise CatalogError(f"unknown baseline {name!r}; expected one of {BASELINE_NAMES}")
    data_dir = _find_data_dir()
    raw = json.loads((data_dir / "baselines" / f"rev5_{name}.json").read_text())
    return frozenset(raw["control_ids"])


@lru_cache(maxsize=1)
def crosswalk() -> Crosswalk:
    data_dir = _find_data_dir()
    raw = json.loads((data_dir / "mappings" / "rev4_to_rev5.json").read_text())
    rows = [
        MappingRow(
            rev4_id=r["rev4_id"],
            rev5_ids=tuple(r["rev5_ids"]),
            relationship=r["relationship"],
            source=r["source"],
        )
        for r in raw["mappings"]
    ]
    return Crosswalk(rows)
